# Change these first
owner: pwv-org # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: juwai
    url: https://www-juwai.pwv.one
  - name: hinabian
    url: https://www-hinabian.pwv.one
  - name: shenjumiaosuan
    url: https://www-shenjumiaosuan.pwv.one/
  - name: himawari
    url: https://www-himawari-japan.pwv.one/
  - name: japan-property
    url: https://www-japan-property.pwv.one/
  - name: inakanoseikatsu
    url: https://inakanoseikatsu.pwv.one
  - name: thinkofliving
    url: https://thinkofliving.pwv.one
  - name: ieichiba
    url: https://www-ieichiba.pwv.one
  
    
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: 
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
